apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/name: taxi
    app.kubernetes.io/part-of: app-taxi
  name: taxi
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: taxi
      app.kubernetes.io/part-of: app-taxi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: taxi
        app.kubernetes.io/part-of: app-taxi
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/cicd/mike-taxi@sha256:e8c2d30700eff5f9461abd3800153434bc386b752c3c58fa2b48800243a1e9f1
        imagePullPolicy: Always
        name: taxi
        ports:
        - containerPort: 8080
        resources: {}
      serviceAccountName: default
status: {}
