apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCnAklGaUD5fXfaeU9N09GnFYDFE0P6TsiHlgLoM5Q+5MGHboOLaNiPiBa6nheDKw8UuHC414TO2h5ip7EP8Fc0zeWvglZn02prGhCDmopjznfDfs7pyqZ3LFnaE62pD7ZFue+1BFp4DroU8oBbL3JYgggCG5WDN/UajqDHTflcOP0db3IwaBmw9PI4uo0yLzOWsXU+3anoQ1jwctlmIOmc/G1/ZHZ/vKMzoy9QQOszckCw76Oem5QoDq1vpSbo0WZGLbwiKVVKCQyeqC9rXziU1l0aXREH4q+KpBxFS/OV6LmpETFSwjf9MLZheDh7Iyx20KWlus4IqrnYjYGjGzeLlnsf2s9c6yT0wHB2CVHBCeNUlyxLUlHPwCBDMZ8kvxSMMfLzXs/hvdvDKp3C+AWZV00sPaaLIlpFxYPGkjdgHaGvxS3eCPonLNhG82+wpnDOoI+vr7dvrAq5rgfsdtTkh3bDRqlF3JwpJdwdl5pz61qdu5Cl1LR4HDYMDK8GdujtzcLmUix2XtHmpqaOJ6MhSUf5rSwzZn6AT5GhSfMcYnHHOTNU+fm1bIBwV1K49A1i8pMs4N4R/QMR4nK1wsEsMz4CWyVsy0IGxqqQ1mQwCA6BvZ9vyLGsPcf6NYWElQi+0h1GnCa1UVU57Dq2G3xeRl8rnVkYpwXRX/roOSirAGoqIhuM9tO6sf9nSudtZ+kou3czKpc38IdJbliIFw9Xe3+PHA==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
