apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: webhook-secret-dev-taxi
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgCQOLatoifFPVbQdI4blx9eF/YyBECFe1j3/TeXiI13fuX/s3hiagr78bdTtzhIKNQsX1refivbrIadSNpG7MzYfVM9FJCamgwYS117zxFcSA0v2ZOa0bqYkWGWA9/kXpnmo/Ruv7EQ+HK2zPiMLpMvdi1d0fVUSiiZbgZcXGUSaUWF0hCB9Ay1LkA20cDQdhFqgl2hXbXQpzTiWIzIhfdD0s/isAxQjv+cinjU76oCPTdcHt7cqEyJY2xfR8zEKwj4K4aJ8aBNcpE+A5djkpaKjqxLa5KDC/FQCR0ApYzzfab4FyA1VM3tkj9lGtfs0eWg8rdPN1KkgiXPZIkXh6KGTnM52c9jPJ3Pbr6btQd7fmWCEqxYqQQWd/pxpkzX3dr+LIrbEabP6t4hXV7QroYO6K0Xz5DwCvJHEeeE4QRHjTdcH1RMG88MJo7+QHpcHt/whgWTIcsgtNFE9oNqSsXVvx8OXaCqpKu/2x/qBERai9WrJ7BYTs3I/GpQ9A0NlpR8UBS5z0oR0TYMM1uoVF6sIJ0Z/aWlCwAe06xn1nzhGP0ZR3uSfA3RkTYlKAU/YHYeLRP+fOMMd6+uhJe9xGG5/kXf8LvrXfqkC/xoGmqaJTgPueUszvvQx4zIT+U8FB8My0JfS8cGfRRh0J/8KurXFZ8f6ZvEDxaD6lL3kA6PICu02TLwPNJg74IdBkxKXlkH7e3kUlV46HvXGtxgxT2GX0MWsg==
  template:
    metadata:
      creationTimestamp: null
      name: webhook-secret-dev-taxi
      namespace: cicd
    type: Opaque
