apiVersion: v1
kind: Namespace
metadata:
  annotations:
    app.openshift.io/vcs-uri: https://github.com/mike4263/taxi-gitops-1613425507.git?ref=main
    uno: dos
  creationTimestamp: null
  name: dev
spec: {}
status: {}
